/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package playground;

import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test
    void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertThat(classUnderTest.someLibraryMethod()).as("someLibraryMethod should return 'true'").isTrue();
    }
}
